/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CDialog: typeof import('./src/components/c-dialog/index.vue')['default']
    CustomDialog: typeof import('./src/components/c-dialog/custom-dialog/index.vue')['default']
    NutOverlay: typeof import('@nutui/nutui-taro')['Overlay']
  }
}
